apiVersion: v1
kind: Service
metadata:
  name: cars-service
spec:
  selector:
    app: cars  # Matches the label in Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
